### ISSUE TITLE
3. The filter “culture” “ecology” and “landscape”

### ISSUE THREAD

**Issue by stina-seattle** [sewardparkstories/sewardparkstories.org#29]
![image](https://cloud.githubusercontent.com/assets/8315247/8295221/6b2fecd6-18f7-11e5-88de-1b86dc7741b1.png)

Pins are on full display if all filters are selected; no filters selected - no pins on map

**Comment by sethvincent** [comment]
http://sewardparkstories.surge.sh/#/list/landscape

**Comment by stina-seattle** [comment]
On mobile/chrome desktop browser:
1. when the list has been filtered
2. when you select one of the pins from that filter
3. All the pins reappear and the selected pin does not remain selected
