### ISSUE TITLE
Site doesn't work in IE

### ISSUE THREAD

**Issue by stina-seattle** [sewardparkstories/sewardparkstories.org#4]
![image](https://cloud.githubusercontent.com/assets/8315247/7194319/8465a68e-e461-11e4-80a1-bda0a7af9e2e.png)

**Comment by stina-seattle** [comment]
Wendy's version
![image](https://cloud.githubusercontent.com/assets/8315247/7194326/96ed3e02-e461-11e4-8bc6-d3031922dd36.png)

**Comment by sethvincent** [comment]
it turns out that this is a complicated issue that has to be solved in the flatsheet server. Issue for that is here: https://github.com/flatsheet/flatsheet/issues/117
