### ISSUE TITLE
Distorted images - Firefox browser

### ISSUE THREAD

**Issue by stina-seattle** [sewardparkstories/sewardparkstories.org#7]
Firefox distorts images, makes them blurry... help?

![firefox issue 1 sps](https://cloud.githubusercontent.com/assets/8315247/7194345/309abb38-e462-11e4-94ba-757412adcc5d.JPG)

**Comment by sethvincent** [comment]
i think that specific photo is just blurry because it is small. it's blurry on my computer in chrome too.

the direct link to the image: https://lh4.googleusercontent.com/-yt4RN3WTvic/VIUz2lDI8FI/AAAAAAAAAZg/cwcRgu1wu9k/h120/Salal-Seward%2BPark-TBancroft.jpg

it's a tiny photo

**Comment by stina-seattle** [comment]
Reworked it
