### ISSUE TITLE
Wishlist #1 (May 1st deadline) - auto HTML tags?

### ISSUE THREAD

**Issue by stina-seattle** [sewardparkstories/sewardparkstories.org#8]
From Wendy : "Can we cut hyperlinked text from Word and paste into FS and the hyperlinks survive?" (The html tags autopopulate)

**Comment by sethvincent** [comment]
maybe we could compromise and use markdown?

then instead of having to type `<a href="http://example.com">link text</a>`

it would be `[link text](http://example.com)`

and that would be a little simpler. eh?

**Comment by stina-seattle** [comment]
Mardown can work. Is there any way to have a text editor on the contributors form?
